name: "Continent Study: Musk vs Trump"
description: "A Picasso-inspired continental analysis of global perspectives through AI and artistic interpretation"
theme: jekyll-theme-minimal

# GitHub Pages configuration
plugins:
  - jekyll-sitemap

# Site settings
title: "Continent Study: Musk vs Trump"
author: "Continental Analysis Team"
url: "https://hannesmitterer.github.io"
baseurl: "/musk_vs_trump"

# Exclude files from processing
exclude:
  - README.md
  - backend/
  - frontend/README.md
  - info-project.txt
  - pyproject.toml

# Custom settings
google_analytics: false
show_downloads: false